name: Test Runner

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: self-hosted
      # - codebuild-test-runner-${{ github.run_id }}-${{ github.run_attempt }}

    # strategy:
      # matrix:
      #   node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v3
        # with:
        #   node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Print Directory
        run: ls -la
      #      - run: npm run build --if-present
      - name: Public IP
        run: curl ifconfig.me
      - run: npm run test
        env:
          AWS_REGION: us-east-1
          
          LOCAL_DYNAMO: "true"
          DYNAMO_ENDPOINT: "http://localhost:8000"
          DATABASE_HOST: 0.0.0.0
          DATABASE_PORT: 5432
          DATABASE_NAME: postgres_db
          DATABASE_USER: postgres_user
          DATABASE_PASSWORD: postgres_password
          REDIS_HOST: 0.0.0.0
          REDIS_PORT: 6379
          BOOTSTRAP_SERVER: localhost:9092


