name: Test Runner

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on:
      - codebuild-test-runner-${{ github.run_id }}-${{ github.run_attempt }}

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Printing directory
        run: ls -la
      - name: Install dependencies
        run: npm i
      #      - run: npm run build --if-present
      - run: npm run test

